config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show, :update]

  root 'static_pages#home'
  get 'about' => 'static_pages#about'

  resources :restaurants do
    resources :reviews
    resources :photos, only: [:new, :create, :destroy]
    member do
      put 'like', to: 'restaurants#like'
      put 'dislike', to: 'restaurants#dislike' 
    end

  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant

  has_attached_file :image, styles: { carousel: "900x500>", medium: "300x300>", thumb: "100x100>" }, default_url: ""
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment :image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  validates :image, attachment_presence: true
  validates_with AttachmentPresenceValidator, attributes: :image
  validates_with AttachmentSizeValidator, attributes: :image, less_than: 1.megabytes
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  acts_as_votable

  has_many :reviews, dependent: :destroy
  has_many :photos, dependent: :destroy

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
  
  validates :name, presence: true

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant

  validates :user_id, presence: true
  validates :restaurant_id, presence: true
  validates :content, presence: true, length: { maximum: 1000 }
  validates :rating,  presence: true, inclusion: (1..5)

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter

  has_many :reviews
  has_many :photos

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", small: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_attachment :avatar, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  validates :avatar, attachment_presence: true
  validates_with AttachmentPresenceValidator, attributes: :avatar
  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 1.megabytes

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) do |user_params|
        user_params.permit(:email, :password, :password_confirmation, :first_name, :last_name)
      end
      devise_parameter_sanitizer.permit(:account_update) do |user_params| 
        user_params.permit(:email, :password, :password_confirmation, :first_name, :last_name)
      end
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @photo = @restaurant.photos.build
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @photo = @restaurant.photos.build(photo_params)
    @photo.user_id = current_user.id
    if @photo.save
      flash[:success] = 'The photo was uploaded!'
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  def destroy

  end

  private

    def photo_params
      params.require(:photo).permit(:image, :caption)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  rescue_from ActionController::RedirectBackError, with: :redirect_to_default

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:success] = "Restaurant saved to database"
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
    @photos = @restaurant.photos
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.liked_by current_user
    redirect_to :back
  end

  def dislike
    @restaurant = Restaurant.find(params[:id])
    @restaurant.downvote_from current_user
    redirect_to :back
  end

  private

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :cuisine, :latitude, :longitude)
    end

    def redirect_to_default
      redirect_to root_path
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = current_user.reviews.build(review_params)
    @review.restaurant_id = params[:restaurant_id]
    if @review.save
      flash[:success] = 'Review successfully saved'
      # fix redirect
      redirect_to root_path
    else
      @restaurant = Restaurant.find(params[:restaurant_id])
      render 'new'
    end
  end

  def show

  end

  def edit
    @review = Review.find(params[:id])
    @restaurant = Restaurant.find(@review.restaurant_id)
  end

  def update
    @review = Review.find(params[:id])
    @restaurant = Restaurant.find(@review.restaurant_id)
    if @review.update(review_params)
      flash[:success] = "Review was successfully edited"
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    Review.find(params[:id]).destroy
    flash[:success] = 'Review successfully deleted'
    redirect_to user_path(current_user)
  end

  private

    def review_params
      params.require(:review).permit(:content, :rating)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = 'User profile updated'
      redirect_to user_path(@user)
    else
      render 'show'
    end

  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :avatar)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.slim
.row
  footer.footer
    small Chantes.cr copyright 2016

app/views/layouts/_header.slim
.row
  nav.navbar.navbar-dark.bg-inverse
    button.navbar-toggler.hidden-sm-up[type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2"]
      |  ☰ 
    #exCollapsingNavbar2.collapse.navbar-toggleable-xs
      = link_to 'Chantes.cr', root_path, class: 'navbar-brand'
      ul.nav.navbar-nav
        li.nav-item
          = link_to 'About', about_path, class: 'nav-link'
        li.nav-item
          = link_to 'Restaurants', restaurants_path, class: 'nav-link'
        li.nav-item
          = link_to 'Add restaurant', new_restaurant_path, class: 'nav-link'
      ul.nav.navbar-nav.pull-xs-right
        - if user_signed_in?
          li.nav-item.dropdown
            a#dropdownMenu1.dropdown-toggle.nav-link[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
              | Account
            .dropdown-menu.dropdown-menu-right
              = link_to current_user, class: 'dropdown-item'
                i class='fa fa-user' aria-hidden='true'
                span Profile
              = link_to '#', class: 'dropdown-item'
                i class='fa fa-cog' aria-hidden='true'
                span Settings
              .dropdown-divider
              = link_to "Log out", destroy_user_session_path, method: "delete", class: 'dropdown-item'
        - else
          li.nav-item
            = link_to 'Log In', new_user_session_path, class: 'nav-link'
          li.nav-item
            = link_to 'Sign Up', new_user_registration_path, class: 'nav-link'

app/views/layouts/application.slim
doctype html
html lang="en" 
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    meta charset="utf-8"
    meta name="robots" content="noindex"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    meta http-equiv="x-ua-compatible" content="ie=edge"
    title Chantes.cr
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'
    = csrf_meta_tags
  body
    .container-fluid
      = render 'layouts/header'

      .row
        .col-sm-8.col-sm-offset-2 id="flash-box"
          - flash.each do |message_type, message|
            - unless message_type.to_s == 'timedout'
              div class=("alert alert-#{message_type} alert-dismissible fade in") role="alert"
                button class="close" type="button" data-dismiss="alert" aria-label="Close"
                  span aria-hidden="true"
                    | &times;
                = message
      = yield
      / = render 'layouts/footer'
      / = debug(params) if Rails.env.development?

app/views/photos/new.slim
.row
  .col-sm-8.col-sm-offset-2
    h5
      = link_to "#{@restaurant.name}:", @restaurant
      |  Add photos

.row.add-photo-section
  .col-sm-4.col-sm-offset-1
    = form_for @photo, url: restaurant_photos_path(@restaurant, @photo), html: { multipart: true } do |f|
      .form-group
        = f.label :image, 'Upload a photo file'
        = f.file_field :image, class: 'form-control-file'
      .form-group
        = f.label :caption
        = f.text_area :caption, class: 'form-control'
        = f.submit 'Upload', class: 'btn btn-default'
  .col-sm-1
  .col-sm-6
    aside
      h6 Guidelines:
      br
      ul
        li Please refrain from posting photos that are poorly lit or blurry.
        li Please keep the photos focused on the business.
        li Photos must be less than 1 MB in size
        li Thank you for contributing!

app/views/restaurants/_modal.slim
.modal.fade id='photo-index' tabindex='-1' role='dialog'
  .modal-dialog.modal-lg role='document'
    .modal-content
      .modal-header
        button type='button' class='close' data-dismiss='modal' aria-label='Close'
          span aria-hidden='true' &times;
        h4 class='modal-title'
      .modal-body
        - if @photos.any?
          .carousel.slide id='main-carousel' data-ride='carousel'

            ol class='carousel-indicators'
              - @photos.each_with_index do |photo, n|
                li data-target='main-carousel' data-slide-to='#{n}' class="#{'active' if n == 0}"

            .carousel-inner role='listbox'
              .carousel-item class='active' 
                  = image_tag @photos.first.image.url(:carousel)
                  .carousel-caption
                    | #{@photos.first.caption}
              - @photos.drop(1).each do |photo|
                .carousel-item
                  = image_tag photo.image.url(:carousel)
                  .carousel-caption
                    p #{photo.caption}

            a class='left carousel-control' href='#main-carousel' role='button' data-slide='prev'
              span.icon-prev aria-hidden='true'
              span.sr-only Previous
            a class='right carousel-control' href='#main-carousel' role='button' data-slide='next'
              span.icon-next aria-hidden='true'
              span.sr-only Next

app/views/restaurants/index.slim
.row
  .col-sm-6
    h2 Restaurants
    ul.restaurants
      - @restaurants.each do |restaurant|
        li
          .card.card-block
            h5.card-title
              = link_to restaurant.name, restaurant_path(restaurant)
            .card-text
              | Address: #{restaurant.address} <br>
              | Cuisine: #{restaurant.cuisine}

app/views/restaurants/new.slim
h1[align="center"]
  | Add a Restaurant
.row
  .col-sm-3.col-sm-offset-1
    = form_for(@restaurant, :html => {class: "form-horizontal", role: "form"}) do |f|
      = render 'shared/errors', object: f.object
      .form-group
        = f.label :name
        = f.text_field :name, class: "form-control"
      .form-group
        = f.label :address
        = f.text_field :address, class: "form-control"
      .form-group
        = f.label :cuisine
        = f.select(:cuisine, options_for_select([['Chinese', 'Chinese'], ['Italian', 'Italian'],['BBQ / Grill', 'BBQ / Grill'],['Costa Rican', 'Costa Rican']]), {}, {class: "form-control"})
      .form-group
        = f.label :latitude
        = f.text_field :latitude, class: 'form-control', id: 'latitude'
      .form-group
        = f.label :longitude
        = f.text_field :longitude, class: 'form-control', id: 'longitude'
      .form-group
        = f.submit class: "btn btn-primary"
  .col-sm-1
  .col-sm-7
    #map-new

javascript:
  $(document).ready(function() {
    L.mapbox.accessToken = '#{Rails.application.secrets.mapbox_api || ENV['MAPBOX_API']}';
    var map = L.mapbox.map('map-new', 'mapbox.streets').setView([9.976733, -84.0088699], 16);
    var marker = L.marker([0, 0])
    var markerLayer
    map.on('click', function(e) {
      console.log(e);
      $('#latitude').val(e.latlng.lat);
      $('#longitude').val(e.latlng.lng);
      map.removeLayer(marker);
      marker = L.marker([e.latlng.lat, e.latlng.lng]).addTo(map);
      map.addLayer(marker)
    });
  });

app/views/restaurants/show.slim
= render 'modal'

.row
  .header-section
    .row
      .col-sm-offset-1.col-sm-4
        h2 = @restaurant.name
      .col-sm-7
        .action-buttons
          .rating-box
      
            = link_to like_restaurant_path(@restaurant), method: :put
              i.fa.fa-thumbs-o-up.fa-2x id='thumbs-up'
            = @restaurant.get_likes.size
        
            = link_to dislike_restaurant_path(@restaurant), method: :put, id: 'thumbs-down'
              i.fa.fa-thumbs-o-down.fa-2x id='thumbs-down'
            = @restaurant.get_dislikes.size

          .review-upload-box
            = link_to "Write review", new_restaurant_review_path(@restaurant), class: "btn btn-primary btn-lg"
            = link_to "Add Photo", new_restaurant_photo_path(@restaurant), class: "btn btn-secondary", id: "add-photo"

    .row.visuals
      .col-sm-offset-1.col-sm-3
        #map-show


      .col-sm-6
        - if @photos.any?
          = image_tag @restaurant.photos.first.image.url(:medium)
          button type='button' class='btn btn-primary btn-small' data-toggle='modal' data-target='#photo-index'
            | See all photos
        - else
          p No photos available
.row
  .review-section
    .row
      .col-sm-offset-1.col-sm-7
        - if @reviews.any?
          .review-box
            ol.reviews
              = render @reviews
      .col-sm-4
        ul.sidebar
          li Address: #{@restaurant.address}
          li Cuisine: #{@restaurant.cuisine}

javascript:
  $(document).ready(function() {
    L.mapbox.accessToken = '#{Rails.application.secrets.mapbox_api || ENV['MAPBOX_API']}';
    var map = L.mapbox.map('map-show', 'mapbox.streets').setView([#{@restaurant.latitude}, #{@restaurant.longitude}], 16);
    var marker = L.marker([#{@restaurant.latitude}, #{@restaurant.longitude}]).addTo(map);

    // For carousel options:
    $('.carousel').carousel({
      pause: true,
      interval: false
    });
  });

app/views/reviews/_form.slim
= form_for [@restaurant, @review] do |f|
  = render 'shared/errors', object: f.object
  .form-group
    = f.label :content
    = f.text_area :content, class: "form-control"
  .form-group
    = f.label :rating
    = f.text_field :rating, class: "form-control"
  .form-group
    = f.submit class: "btn btn-primary"

app/views/reviews/_review.slim
li id="review-#{review.id}" class='review-li'
  .row
    .col-sm-4
      = review.user.email
    .col-sm-8
      .row
        = review.rating
      .row
        = review.content

app/views/reviews/edit.slim
.row
  h2 align='center' Edit review for #{@restaurant.name}
  .col-sm-offset-4.col-sm-4
    = render 'form'

app/views/reviews/new.slim
.row
  h2 align="center" Write a review for #{@restaurant.name}
  .col-sm-offset-4.col-sm-4
    = render 'form'

app/views/shared/_errors.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      |  The form contains 
      = pluralize(object.errors.count, "error")
      | . 
    ul
      - object.errors.full_messages.each do |msg|
        li
          = msg

app/views/static_pages/about.slim
.row
  h2 align="center" About

app/views/static_pages/home.slim
.row
  .col-sm-8.col-sm-offset-2
    h1 Welcome to Chantes.cr
    #map

javascript:
  L.mapbox.accessToken = '#{Rails.application.secrets.mapbox_api || ENV['MAPBOX_API']}';
  var map = L.mapbox.map('map', 'mapbox.streets').setView([9.976733, -84.0088699], 16);
  map.on('click', function(e){
    alert(e.latlng);
    console.log(e);
  });

app/views/users/show.slim
.row
  .col-sm-3.col-sm-offset-2
    = image_tag @user.avatar.url(:medium), id: 'user-avatar'
    = form_for @user, method: :patch, url: user_path(@user), html: { multipart: true } do |f|
      .form-group
        = f.label :avatar, 'Change Profile Pic:'
        = f.file_field :avatar, class: 'form-control-file'
        = f.submit 'Submit', class: 'btn btn-default btn-sm'

  .col-sm-7
    h5 #{@user.first_name} #{@user.last_name}
    .profile-stats
      i class='fa fa-list-alt' aria-hidden='true'
      span #{@user.reviews.count} Reviews
      i class='fa fa-camera' aria-hidden='true'
      span Photos
      i class='fa fa-users' aria-hidden='true'
      span Friends

.row#user-reviews
  .col-sm-8.col-sm-offset-2
    - if @user.reviews.any?
      h4 Your Reviews:
      ol.user-reviews
        - @user.reviews.each do |review|
          li.card.card-block
            h6 #{Restaurant.find(review.restaurant_id).name}
            span.pull-xs-left
              = review.rating
            small.pull-xs-right
              | Posted 
              = time_ago_in_words(review.created_at)
              |  ago
            br
            p.card-text
              = review.content
            .review-actions
              = link_to "Edit", edit_restaurant_review_path(review.restaurant_id, review), class: "btn btn-sm btn-primary"
              = link_to "Delete", restaurant_review_path(review.restaurant_id, review), method: :delete,
                                           data: { confirm: "Are you sure you want to delete the review?"},
                                           class: "btn btn-sm btn-danger"
    - else
      p No reviews written yet